{
 "title": "UserDataExpenseManagerDashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total EXPENSE Amount Per Day",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "expensemanagerdb",
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(transaction_date) AS time,\r\n  SUM(amount) AS value,\r\n  user_id AS metric\r\nFROM transaction_info\r\nWHERE transaction_type = 'EXPENSE'\r\nGROUP BY transaction_date, user_id\r\nORDER BY transaction_date;\r\n"
    }
   ]
  },
  {
   "title": "Category distribution",
   "type": "barchart",
   "description": "Expense category distribution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "expensemanagerdb",
     "rawSql": "SELECT\r\n    category AS metric,\r\n    SUM(amount) AS value\r\nFROM transaction_info\r\nWHERE transaction_type = 'EXPENSE'\r\nGROUP BY category\r\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "Expense vs Income",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "expensemanagerdb",
     "rawSql": "SELECT\r\n  'Expense' AS metric1,\r\n  SUM(amount) AS Expense\r\nFROM transaction_info\r\nWHERE transaction_type = 'EXPENSE'\r\nUNION ALL\r\nSELECT\r\n  'Income' AS metric2,\r\n  SUM(amount) AS Income\r\nFROM transaction_info\r\nWHERE transaction_type = 'INCOME';\r\n"
    }
   ]
  },
  {
   "title": "Expenses per week",
   "type": "timeseries",
   "description": "Week starts on Monday and end on Sunday.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "expensemanagerdb",
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(STR_TO_DATE(CONCAT(yearweek, ' Monday'), '%X%V %W')) AS time,\r\n    total_amount AS value\r\nFROM (\r\n         SELECT\r\n             YEARWEEK(transaction_date, 1) AS yearweek,\r\n             SUM(amount) AS total_amount\r\n         FROM transaction_info\r\n         WHERE transaction_type = 'EXPENSE'\r\n         GROUP BY YEARWEEK(transaction_date, 1)\r\n     ) AS weekly\r\nORDER BY yearweek;"
    }
   ]
  }
 ]
}